### ISSUE TITLE
viewing a commit's file changes is broken

### ISSUE THREAD

**Issue by dbkaplun** [FredrikNoren/ungit#734] opened 2016-04-15 13:58 UTC
When I click on a previous commit bubble, I am able to see a list of files that were changed as well as the number of lines changed in each file. However, when I click on a file, I am unable to see the actual changes made to that file, although I can see the UI twitch on click and `Event: Object {event: "graph-render"}` appears in the JS console.

ungit@0.10.1

**Comment by waldyrious** [comment] 2016-04-15 15:58
Same here.

**Comment by lfx** [comment] 2016-04-15 21:22
Using ungit@0.10.1, can't reproduce.

@dbkaplun, @waldyrious have you updated ungit recently?

**Comment by codingtwinky** [comment] 2016-04-16 20:05
I cannot reproduce this but if this is a pretty big bug.  

Could you share client log, server log and the file name, and sha1 of diff you are trying to see?

**Comment by waldyrious** [comment] 2016-04-18 00:19
This apparently only happens if I run `ungit` from a subdirectory of the repo, rather than its root. HTH  :)

**Comment by campersau** [comment] 2016-04-18 13:16
Ah, so I can reproduce it too.

The problem is that if you are in a subdirectory the [`filename`](https://github.com/FredrikNoren/ungit/blob/master/source/git-promise.js#L286) is always relatative to the git directory but git diff wants an relative path from the executing directory.

For example if you are in the subdirectory `components` of the ungit project the git diff command looks like this: `ungit/components> git diff a49c657cfa1bab61d740cf1fc3a72c5f15b2ed26^ a49c657cfa1bab61d740cf1fc3a72c5f15b2ed26 -- clicktests/test.generic.js`
But it should have been this: `ungit/components> git diff a49c657cfa1bab61d740cf1fc3a72c5f15b2ed26^ a49c657cfa1bab61d740cf1fc3a72c5f15b2ed26 -- ../clicktests/test.generic.js`

(Notice the `../` in the filename.)

**Comment by codingtwinky** [comment] 2016-04-18 16:28
Yup, I will be closing #706 in lieu of this ticket.

I think this would be a great time to start using absolute path within ungit

**Comment by dbkaplun** [comment] 2016-04-18 16:52
I run ungit as a daemon, as outlined here (with a few insignificant modifications): https://github.com/FredrikNoren/ungit/wiki/Startup-Script-for-Mac-OS-X. If this is intended usage, ungit should not rely on the cwd at all.

**Comment by codingtwinky** [comment] 2016-05-01 19:39
@dbkaplun This now works for me and master branch should work for you but please feel free to reopen if this is still a problem.

**Closed** 2016-05-01 19:38 UTC

**Comment by dbkaplun** [comment] 2016-05-02 03:13
Works now, thanks @codingtwinky!
