### ISSUE TITLE
Too many unstaged files

### ISSUE THREAD

**Issue by PedroKTFC** [FredrikNoren/ungit#569] opened 2015-06-02 21:20 UTC
On windoze I am frequently seeing this pop up message even when there aren't (in my opinion!) so many file. I'd never seen it until the latest version.

Too many unstaged files
It is recommended to use command line as ungit may be too slow.

**Comment by campersau** [comment] 2015-06-02 21:34
This change was introduced in https://github.com/FredrikNoren/ungit/pull/508 .
Ungit displays the warning if there are more than [50](https://github.com/FredrikNoren/ungit/pull/508/files#diff-fc0b5a5371d3847934024564c29fd78cR7) files in staging.

How many files do you have in staging? How many files would you consider as "too many"?

**Comment by PedroKTFC** [comment] 2015-06-02 22:57
I've seen it with about 100, possibly fewer. The problem is when I click the load anyway button, it always hangs. This is making it unusable (try a Drupal upgrade!).

**Comment by FredrikNoren** [comment] 2015-06-03 02:34
@codingtwinky maybe 50 was a little conservative. Think it can probably handle hundreds on most systems with no problem. Maybe we can increase to 200 at least?

**Comment by Ajedi32** [comment] 2015-06-03 14:18
If it's hanging for him with ~100 files though then maybe 50 isn't too conservative...

Maybe there's some way performance could be improved? It shouldn't be *that* computationally intensive to render the path names of a couple thousand files in the browser. Most of the work probably goes into rendering the diffs, right? And you should only need to do that after the user clicks on a specific file to expand the diff.

**Comment by PedroKTFC** [comment] 2015-06-03 20:00
It never used to hang in earlier versions before this change, even with hundreds of files.

**Comment by campersau** [comment] 2015-06-05 19:30
@PedroKTFC is ungit running while your files get changed or do you load ungit afterwards?
For the first case I submitted a [PR](https://github.com/FredrikNoren/ungit/pull/575) which should fix the "hanging" issue. (It doesn't increase the unstaged file limit)

**Comment by PedroKTFC** [comment] 2015-06-06 12:31
@campersau it certainly hangs when I'm not making any changes. I often just run it up before I do any work, I get the too many files error, click on the load anyway option, and after the pop up disappears, nothing more happens.

**Comment by campersau** [comment] 2015-06-06 14:41
@PedroKTFC thanks so my fix is not related to this.
What version of ungit do you use? The current 0.9.x line has serveral bugs with windows (which are now fixed in master). Maybe your problem is not caused by too many files but with the windows related bugs?
Because I currently can't reproduce it on windows (using the current master).

**Comment by PedroKTFC** [comment] 2015-06-06 15:03
0.9.2

**Comment by campersau** [comment] 2015-06-06 15:24
Okay so that is probably the real issue here.
@PedroKTFC can you try out the latest master with `npm install -g git+https://github.com/FredrikNoren/ungit.git` and check if the "hanging" problem persists?

**Comment by PedroKTFC** [comment] 2015-06-07 22:19
Now it doesn't work at all! :o(

**Comment by campersau** [comment] 2015-06-08 10:15
Ups using npm to install ungit from git repo does not work. Sorry...
Try [this](https://github.com/FredrikNoren/ungit/issues/542#issuecomment-104479649) instead: `git clone https://github.com/FredrikNoren/ungit.git && cd ungit && npm install && npm install grunt-cli && ./node_modules/.bin/grunt && npm install -g .`

**Comment by PedroKTFC** [comment] 2015-06-10 09:18
That worked so I can now use git again. Unfortunately, I don't currently
have many files in any repository but I'll update as soon as I do. Thanks.

**Comment by PedroKTFC** [comment] 2015-06-10 21:40
Have now tried it out with enough files to get the warning and it seems to work! Thank you.

**Comment by campersau** [comment] 2015-06-10 21:42
Great! So this issue can be closed right?

**Comment by PedroKTFC** [comment] 2015-06-10 21:52
For now! ;o)

**Closed** 2015-06-24 00:44 UTC
