### ISSUE TITLE
feature: Patch possibility

### ISSUE THREAD

**Issue by basdek** [FredrikNoren/ungit#552] opened 2015-05-14 08:48 UTC
This git tool would be even more awesome than it is right now if it featured the possibility to patch (partially stage / commit) source code files.

**Comment by codingtwinky** [comment] 2015-05-15 03:15
Just to clarify, you are looking for import/export patch right?

@Ajedi32 you might be able to answer this question, but what is the difference between patch vs cherrypick other then .patch file?  Does one fits better over another for Ungit?  Because I was gonna do similar thing where cherrypick via given git commit url.

**Comment by Ajedi32** [comment] 2015-05-15 03:44
It sounds like what @basdek is talking about here is `git add --patch`. It's basically a way of letting you stage individual lines of a file, rather than staging all the changes in the file at once. Importing patches is something different entirely.

**Comment by basdek** [comment] 2015-05-15 09:35
Indeed I was talking about staging different lines, individual lines.

On Friday, May 15, 2015, Andrew Meyer <notifications@github.com> wrote:

> It sounds like what @basdek <https://github.com/basdek> is talking about
> here is git add --patch. It's basically a way of letting you stage
> individual lines of a file, rather than staging all the changes in the file
> at once. Importing patches is something different entirely.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FredrikNoren/ungit/issues/552#issuecomment-102245250>.
>


-- 
Met vriendelijke groet,


Bas de Kwant
(basdekwant@gmail.com)

**Comment by codingtwinky** [comment] 2015-05-16 21:56
so this is a duplicate of #169 ?

**Comment by FredrikNoren** [comment] 2015-06-03 02:35
Closing this one as a duplicate

**Closed by FredrikNoren** 2015-06-03 02:35 UTC
Labels: duplicate
