### ISSUE TITLE
A problem with launching of ungit

### ISSUE THREAD

**Issue by polyglot0027** [FredrikNoren/ungit#768] opened 2016-07-10 07:43 UTC
Hello everyone! I have a little problem with ungit. There is an error when I try to launch unget by command promprt on Win OS. It's curious that an error depends upon version of nodejs. Also I've been trying to conjure with the npm file by editing the one, but anyway nothing help. It seems like I have to throw Win away and just should install Linux :) I'll be totally grateful if you give any ideas to solve this problem. Thanks in advance!
![error](https://cloud.githubusercontent.com/assets/18975138/16712274/f530297a-468a-11e6-988c-cbcd780b301b.gif)

**Comment by FredrikNoren** [comment] 2016-07-10 16:16
I'm not 100% sure what the problem is here, but seems like it's something around npm, and it looks like you're on version 2. We just released a new version to fix #766, which should ensure that the npm version is >3, so I'd say try upgrading. It might also help switching to another console. Closing for now but re-open if that doesn't help.

**Closed by FredrikNoren** 2016-07-10 16:16 UTC

**Comment by polyglot0027** [comment] 2016-07-10 17:00
Thanks a lot for an answer, Frederik! I made upgrade of npm, but the error didn't go. So I decided to reinstall ungit down to 0.10.1 version as it was said in #766 and thereby the problem was solved :)

**Comment by FredrikNoren** [comment] 2016-07-10 17:01
If you have time, can you try 0.10.3? We just pushed it and I hope it's
solving that issue, but would be good to verify

**Comment by polyglot0027** [comment] 2016-07-10 17:03
No problem! Just a minute

**Comment by polyglot0027** [comment] 2016-07-10 17:07
Yep, it works perfectly. Thanks one more time! :)

**Comment by FredrikNoren** [comment] 2016-07-10 17:11
Great, thanks for testing!

**Comment by polyglot0027** [comment] 2016-07-10 17:14
Anytime, Fredrik! :)
