### ISSUE TITLE
Compiling error when install 0.9.1

### ISSUE THREAD

**Issue by renkun-ken** [FredrikNoren/ungit#528] opened 2015-04-06 01:43 UTC
Run in Windows 8.1 x64 with Admin and node.js 0.12.1.

```
C:\Windows\system32>npm install -g ungit
|


> typechecker@2.0.8 preinstall C:\Users\Kun\AppData\Roaming\npm\node_modules\ung
it\node_modules\getmac\node_modules\extract-opts\node_modules\typechecker
> node ./cyclic.js

-
> execSync@1.0.2 install C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\nod
e_modules\diff2html\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn node-gyp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp' }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
\
```

When the installation completed, I run `ungit` and visit localhost:8448 in browser. The home screen works fine but no repo can be loaded and the progress bar keeps hanging at a near-end point for quite a while then the connection is lost.

I reinstall ungit and the command line becomes

```
C:\Users\Kun>ungit
info: BugTracker set version: 0.9.1
options.options is deprecated. Use options.args instead.
Ungit server already running
Browse to http://localhost:8448/#/repository?path=C%3A%5CUsers%5CKun
info: BugTracker set user hash

C:\Users\Kun>
```

and I can't open any ungit page any more.

**Comment by LeeWarner** [comment] 2015-04-06 15:02
I'm having the same issue.  Same OS

**Comment by FredrikNoren** [comment] 2015-04-07 01:32
@renkun-ken can you try restarting your computer? seems like the last thing there is some lingering ungit process running

**Comment by renkun-ken** [comment] 2015-04-07 01:42
I tried terminating all node.exe related to ungit but it does not work :(

**Comment by FredrikNoren** [comment] 2015-04-07 01:50
I just tried installing ungit 0.9.1 on a win7 machine and that seems to work. Can you try uninstalling ungit, rebooting and then reinstalling it? (My best guess is that something went wrong in the installation process)

**Comment by antograssiot** [comment] 2015-04-07 04:02
@FredrikNoren Same issue for me, I've tried the above without success.
Win 8.1 x64
node v0.12.6

**Comment by codingtwinky** [comment] 2015-04-07 05:06
Could this be related to https://github.com/TooTallNate/node-gyp/issues/559?

**Comment by antograssiot** [comment] 2015-04-07 10:20
@codingtwinky unfortunately I have the same problem on win7 x64

**Comment by wormeyman** [comment] 2015-04-07 17:39
I'm having this as well.

**Comment by mesosteros** [comment] 2015-04-08 15:45
Same here.
Windows 8.1 x64
Node v0.12.1

@wormeyman instructions for regression worked.

In addition to the install errors when trying to run ungit 0.9.1 a lot of extra command line windows pop up (one is for git, I can't remember the other one)

**Comment by ylecuyer** [comment] 2015-04-08 21:13
I had to revert to 0.8.4 too however I'm under linux.
I think it is related to the python version but I wasn't able to force it to python2

**Comment by wormeyman** [comment] 2015-04-08 21:26
Hmm I do have python 3 installed on my windows machine.

**Comment by renkun-ken** [comment] 2015-04-09 01:05
I'm using python 2.7.8 (anaconda 2.1.0 64-bit distribution).

**Comment by codingtwinky** [comment] 2015-04-09 03:28
[Here](https://github.com/TooTallNate/node-gyp/issues/154#issuecomment-33331216) is another thread that is possibly have fix for this issue. 
I can't reproduce this error so I'm not sure what to do...

**Comment by wormeyman** [comment] 2015-04-09 15:59
###Switching to a 32bit version of Node did seem solve the problem for me.

`
C:\Users\ejohnson\Documents\GitHub> npm update -g ungit
-


> typechecker@2.0.8 preinstall C:\Users\ejohnson\AppData\Roaming\npm\node_modules\ungit\node_modules\getmac\node_modules\extract-opts\node_modules\typechecker
> node ./cyclic.js

\


> execSync@1.0.2 install C:\Users\ejohnson\AppData\Roaming\npm\node_modules\ungit\node_modules\diff2html\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn node-gyp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp' }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
|
> ws@0.4.32 install C:\Users\ejohnson\AppData\Roaming\npm\node_modules\ungit\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

`

**Comment by wormeyman** [comment] 2015-04-09 16:17
The error in my builderror.log

`gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:108:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ejohnson\AppData\Roaming\npm\node_modules\ungit\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
`

**Comment by FredrikNoren** [comment] 2015-04-11 18:08
@mesosteros @codingtwinky I wonder if the extra command line windows opening is a result from switching to child_process.spawn? :/

**Comment by FredrikNoren** [comment] 2015-04-11 18:12
@codingtwinky Hm in the first comment @renkun-ken made there's a reference to https://www.npmjs.com/package/execSync, which seems to be diff2html uses, but it's stated explicitly on the execSync thing that you shouldn't use that in production. I wonder if that's a problem some how. Maybe we should try bundling diff2html differently? @renkun-ken if you can, could you try cloning ungit and removing diff2html from the package.json and see if you can `npm install` then? Just to see if that's indeed the problem?

**Comment by codingtwinky** [comment] 2015-04-11 18:52
Could you try this?

1. vi bin/diff2html
2. change `require("../src/main.js").interpret(process.argv);` -> `require("../src/diff2html.js");`

With whatever equivalent of windows...

**Comment by FredrikNoren** [comment] 2015-04-13 04:32
I'll keep this open until we've verified that the fix actually solved the problem

**Comment by mesosteros** [comment] 2015-04-13 09:11
Nope didn't solve it. I've checked the extra cmd windows that pop up: they are both for git.exe.
During the update process I got the following errors and warnings:

C:\Users\mesos_000\AppData\Roaming\npm\node_modules\ungit\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C
:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\mesos_000\AppData\Roaming\npm\node_modules\ungit\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj(18,3): error MSB4
019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Users\mesos_000\AppData\Roaming\npm\node_modules\ungit\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcxproj(18,3): error MSB4
019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Users\mesos_000\AppData\Roaming\npm\0ungit-credentials-helper -> C:\Users\mesos_000\AppData\Roaming\npm\node_modules\ungit\bin\credentials-helper
C:\Users\mesos_000\AppData\Roaming\npm\ungit -> C:\Users\mesos_000\AppData\Roaming\npm\node_modules\ungit\bin\ungit
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc requires strong-pm@'^1.6.0' but will load
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-pm,
npm WARN unmet dependency which is version 3.1.5
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-workspace\node_modules\loop
back requires debug@'~2.0.0' but will load
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-workspace\node_modules\debu
g,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-workspace\node_modules\loop
back requires inflection@'~1.4.2' but will load
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\inflection,
npm WARN unmet dependency which is version 1.7.0
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-workspace\node_modules\loop
back-datasource-juggler requires debug@'^2.1.1' but will load
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-workspace\node_modules\debu
g,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-workspace\node_modules\loop
back-datasource-juggler requires lodash@'~3.0.1' but will load
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-workspace\node_modules\loda
sh,
npm WARN unmet dependency which is version 2.4.1
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\node-inspector\node_modules\rc requires ini@'~1.1.0' but will load
npm WARN unmet dependency C:\Users\mesos_000\AppData\Roaming\npm\node_modules\strongloop\node_modules\ini,
npm WARN unmet dependency which is version 1.3.3

When starting ungit, I also get the following when I start the ungit process:
options.options is deprecated. Use options.args instead.

I'm going to reverting back to 0.8.4 again.

**Comment by codingtwinky** [comment] 2015-04-14 02:57
Multiple cmd windows opening is expected as we haven't located the cause of it yet.  Dependency bump was in hopes to fix compilation error, which it seems to have solved as I think you were able install and start ungit despite various warnings.  Could you confirm the successful installation?

Also could you clean the node global directory before next installation?  Especially `C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin` as it is no longer needed.

**Comment by renkun-ken** [comment] 2015-04-14 03:26
I use the following command line to install the latest commit:

```
npm install -g git+ssh://git@github.com:FredrikNoren/ungit.git
```

and the install completes without error.

and I run `ungit` in command line then the command line shows

```
C:\Users\Kun\Documents\Workspaces\ungit>ungit
info: BugTracker set version: 0.9.1
options.options is deprecated. Use options.args instead.
Ungit server already running
Browse to http://localhost:8448/#/repository?path=C%3A%5CUsers%5CKun%5CDocuments
%5CWorkspaces%5Cungit
info: BugTracker set user hash
```

and a web page shows

```
Error: write EPIPE
   at exports._errnoException (util.js:746:11)
   at Socket._writeGeneric (net.js:681:26)
   at Socket._write (net.js:700:8)
   at doWrite (_stream_writable.js:301:12)
   at writeOrBuffer (_stream_writable.js:288:5)
   at Socket.Writable.write (_stream_writable.js:217:11)
   at Socket.write (net.js:625:40)
   at Console.log (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\winston\lib\winston\transports\console.js:86:20)
   at emit (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\winston\lib\winston\logger.js:186:17)
   at C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\async\lib\async.js:125:13
   at Array.forEach (native)
   at _each (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\async\lib\async.js:46:24)
   at Object.async.each (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\async\lib\async.js:124:9)
   at Logger.log (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\winston\lib\winston\logger.js:214:9)
   at Object.winston.(anonymous function) [as log] (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\winston\lib\winston.js:87:34)
   at Object.target.(anonymous function) [as error] (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\winston\lib\winston\common.js:52:18)
   at C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\source\server.js:343:11
   at Layer.handle_error (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\layer.js:58:5)
   at trim_prefix (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:300:13)
   at C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:321:12)
   at next (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:261:10)
   at Layer.handle_error (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\layer.js:54:12)
   at trim_prefix (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:300:13)
   at C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:321:12)
   at next (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:261:10)
   at Layer.handle_error (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\layer.js:54:12)
   at trim_prefix (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:300:13)
   at C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:321:12)
   at next (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:261:10)
   at Layer.handle_error (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\layer.js:54:12)
   at trim_prefix (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:300:13)
   at C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:321:12)
   at next (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:261:10)
   at Layer.handle [as handle_request] (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\layer.js:84:5)
   at trim_prefix (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:302:13)
   at C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:321:12)
   at next (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:261:10)
   at expressInit (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\middleware\init.js:23:5)
   at Layer.handle [as handle_request] (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\layer.js:82:5)
   at trim_prefix (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:302:13)
   at C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:321:12)
   at next (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:261:10)
   at query (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\middleware\query.js:28:5)
   at Layer.handle [as handle_request] (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\layer.js:82:5)
   at trim_prefix (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:302:13)
   at C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:321:12)
   at next (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:261:10)
   at Function.proto.handle (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\router\index.js:166:3)
   at EventEmitter.app.handle (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\application.js:170:10)
   at Server.app (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\express\lib\express.js:28:9)
   at Manager.handleRequest (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\socket.io\lib\manager.js:588:28)
   at Server.<anonymous> (C:\Users\Kun\AppData\Roaming\npm\node_modules\ungit\node_modules\socket.io\lib\manager.js:119:10)
   at Server.emit (events.js:110:17)
   at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
   at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
   at Socket.socketOnData (_http_server.js:343:22)
   at Socket.emit (events.js:107:17)
   at readableAddChunk (_stream_readable.js:163:16)
   at Socket.Readable.push (_stream_readable.js:126:10)
   at TCP.onread (net.js:529:20) 
```

**Comment by mesosteros** [comment] 2015-04-14 08:51
I did as you said @codingtwinky and ungit installed only with warnings and no errors. However after I run ungit, it begins loading the localhost:8448 page and immediately looses connection. Then the issue of "ungit server already running" occurs in the cmd and I can't access the page.

**Comment by codingtwinky** [comment] 2015-04-15 03:56
Thanks, good to know that we got a piece of a puzzle.

For multiple spawns, I think this is due to https://github.com/foreverjs/forever-monitor/issues/86 and we might need to downgrade it until the fix is in.  However, I'm not sure if this is the last of the bugs as I fear there maybe more to reveal.

**Comment by yanosh-igor** [comment] 2015-04-15 09:35
I have same issue on node 0.12.

**Comment by FredrikNoren** [comment] 2015-04-21 02:28
Ok the original issue should have been fixed as well as the other issues mentioned, and a new version has been released: 0.9.2. Please try it, and if there are any issues please open separate tickets for those. I'm closing this one as the original issue posted is fixed.

**Closed by FredrikNoren** 2015-04-21 02:28 UTC

**Comment by renkun-ken** [comment] 2015-04-21 02:38
Thanks, the latest release works for me!

**Comment by mesosteros** [comment] 2015-04-21 08:53
Latest release also works for me. And no more extra cmd windows are popping up :)
:+1:

**Comment by antograssiot** [comment] 2015-04-21 09:25
awesome, thank's again for this great tool :clap:

**Comment by wormeyman** [comment] 2015-04-21 14:58
Thanks for the hard work :+1:

**Comment by LeeWarner** [comment] 2015-04-21 15:26
I'm good now too!  Thanks for this tool, it has done wonders for helping me with understanding git and being able to visualize things.
