### ISSUE TITLE
api/baserepopath not found

### ISSUE THREAD

**Issue by linquize** [FredrikNoren/ungit#579] opened 2015-06-12 13:43 UTC
In firefox console, I found this error
http://localhost:8448/api/baserepopath HTTP 404

ungit v0.9.2-29-g908c1eb on linux

**Comment by campersau** [comment] 2015-06-12 16:50
Yes, this is currently the correct behavior see [here](https://github.com/FredrikNoren/ungit/blob/master/source/git-api.js#L514) and is expected see [here](https://github.com/FredrikNoren/ungit/blob/master/components/repository/repository.js#L61-L64).

The method returns a 404 if the current folder is the root of the repo. But if you are in a subfolder / submodule it returns the "base" repo path. I think we should just remove the first traversal [here](https://github.com/FredrikNoren/ungit/blob/master/source/git-api.js#L499) so that the type of the returned value is consistent.

**Comment by FredrikNoren** [comment] 2015-06-24 00:45
Closing since this is expected behaviour

**Closed by FredrikNoren** 2015-06-24 00:45 UTC
