### ISSUE TITLE
Lately, whenever I try to run ungit on Cloud9, it crashes. Older installations continue to work, but whenever I try to run a new setup on c9, I get the following in the console:

### ISSUE THREAD

**Issue by vgr2** [FredrikNoren/ungit#1138] opened 2018-09-15 07:59 UTC
```
Took 1768ms to start server.
Navigate to https://0.0.0.0:8081/#/repository?path=%2Fhome%2Fubuntu%2Fworkspace%2Fweb2py%2Fapplications%2Fexamples
failed to navigate to https://0.0.0.0:8081/#/repository?path=%2Fhome%2Fubuntu%2Fworkspace%2Fweb2py%2Fapplications%2Fexamples Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/ungit/node_modules/opn/index.js:84:13)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

**Comment by campersau** [comment] 2018-09-16 07:43
This error is now expected if you start ungit environments which don't have a browser. The server is still running. See https://github.com/FredrikNoren/ungit/issues/1115#issuecomment-415990234
Also you now have to specify the IP on which interface ungit should be accessible to the public. You can set `--ungitBindIp 0.0.0.0` to restore the default behavior of the previous ungit versions. See https://github.com/FredrikNoren/ungit/issues/1115#issuecomment-417947594

Closing as duplicate of https://github.com/FredrikNoren/ungit/issues/1115

**Closed by campersau** 2018-09-16 07:43 UTC

**Comment by vgr2** [comment] 2018-10-02 20:09
Thanks
