### ISSUE TITLE
Unable to access ungit after Windows 10 upgrade

### ISSUE THREAD

**Issue by tanstry** [FredrikNoren/ungit#638] opened 2015-10-30 14:24 UTC
Hi,

I upgraded to Windows 10 then updating node.js, npm and install last ungit version

Ungit seems starting well but I cannot access to ungit via any kind of web browsers!

```
info: BugTracker set version: 0.9.3
info: BugTracker set user hash
info: BugTracker set version: 0.9.3
2015-10-30T14:15:14.553Z - info: socket.io started
2015-10-30T14:15:14.563Z - info: Listening on port 8448
Browse to http://localhost:8448/#/repository?path=...
Took 827ms to start server.
## Ungit started ##
2015-10-30T14:15:14.570Z - info: BugTracker set user hash
```
This is likely a Windows bug but does anyone met the same issue?

**Comment by codingtwinky** [comment] 2015-11-02 05:03
Do you have a browser client log to share?

Are you using new spartan ie?

**Comment by tanstry** [comment] 2015-11-02 15:02
Nothing in the logs.

I tried with:
- Firefox: timeout
- Chrome: ERR_CONNECTION_TIMED_OUT
- IE Edge: unreachable page

I found some known causes on forums and try but nothing better:
- disabled IIS which came up with Windows 10
- tried to find World Wide Web Publishing Service: not running on my PC
- allowed Localhost Loopback in Edge

**Comment by codingtwinky** [comment] 2015-11-02 16:42
So port 8448 is unreachable, seems like your traffic to 8448 is being denied.  Is there [over active firewall policy](http://windows.microsoft.com/en-us/windows/open-port-windows-firewall#1TC=windows-7) or any other security softwares that may have caused this?

**Comment by tanstry** [comment] 2015-11-04 08:11
Thanks for helping.

I disabled the firewall, uninstall the antivirus, nothing changed...
I installed apache to check if the problem was just related to port 8448, but localhost is not reachable at all...

**Comment by codingtwinky** [comment] 2015-11-05 01:51
No problem.  can you confirm that this is not ungit problem as it seems that all http access are being blocked for local host.  If so, I would like to close this ticket.

**Comment by tanstry** [comment] 2015-11-05 09:33
Sure, this is a Windows problem. This is just frustrating not being able to use ungit...

**Comment by Ajedi32** [comment] 2015-11-05 14:25
I don't think this is necessarily something caused by Windows either though. I can access localhost on my laptop running Windows 10 just fine. Either way, if you can't access Apache either then it's very likely this problem has nothing to do with ungit.

**Comment by tanstry** [comment] 2015-11-05 21:22
Ungit was running fine just before the Windows 10 upgrade...seems like something goes wrong in network configuration

**Comment by codingtwinky** [comment] 2015-11-07 01:39
Closing as issue seems to be unrelated to ungit.

**Closed by codingtwinky** 2015-11-07 01:39 UTC
